steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "Building with branch: $BRANCH_NAME"
      echo "***********************"

- id: 'tf init'
  name: 'hashicorp/terraform:latest'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
       cd terraform; terraform init; cd -

- id: 'tf plan'
  name: 'hashicorp/terraform:latest'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      cd terraform; terraform plan; cd -

- id: 'tf apply'
  name: 'hashicorp/terraform:latest'
  entrypoint: 'sh'
  timeout: '1800s'
  args: 
  - '-c'
  - |
      cd terraform; terraform apply -auto-approve; cd -
